title: ğŸŠ's Website
"title.background": "#002b36"
logo: ./1.png
description: ğŸ’–ğŸ‘ğŸ§ğŸ°ğŸµğŸ“·ğŸ”®
google_analytics:
theme: jekyll-theme-minimal
url: https://kimgyuring.github.io/PoeticCodeForNature/
